project:
  type: website
  output-dir: docs
  render: 
    - "*/index.qmd"
    - "index.qmd"

website:
  title: Chisocnet Summer School 2024 -- ERGMs
  
  navbar: 
    left:
      - text: Home
        href: index.qmd
      - text: Fundamentals
        href: 00-fundamentals/index.qmd
      - text: Introduction
        href: 01-intro-to-ergms/index.qmd
      - text: Advanced topics
        href: 02-advanced-ergms/index.qmd
      - text: New developments
        href: 03-new-topics/index.qmd
    right:
      - icon: github
        href: https://github.com/gvegayon/chisocnet-ss2024

format:
  html:
    html-math-method: katex
    bibliography: ../references.bib
    toc: true
    number-sections: true
    embed-resources: true
